# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableChangesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('instance_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('field_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='tablechangeslog',
            index_together=set([('table_name', 'instance_id')]),
        ),
    ]
