# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-28 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablechangelogger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablechangeslog',
            name='field_value',
        ),
        migrations.AddField(
            model_name='tablechangeslog',
            name='new_field_value',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tablechangeslog',
            name='old_field_value',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
