# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-29 07:55
from __future__ import unicode_literals

from django.db import migrations
import tablechangelogger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tablechangelogger', '0002_auto_20190528_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablechangeslog',
            name='new_field_value',
        ),
        migrations.RemoveField(
            model_name='tablechangeslog',
            name='old_field_value',
        ),
        migrations.AddField(
            model_name='tablechangeslog',
            name='log',
            field=tablechangelogger.fields.LoggedField(max_length=1000, null=True),
        ),
    ]
