# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-05-29 08:18
from __future__ import unicode_literals

from django.db import migrations
import tablechangelogger.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tablechangelogger', '0003_auto_20190529_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechangeslog',
            name='log',
            field=tablechangelogger.fields.LoggedField(max_length=10485000, null=True),
        ),
    ]
