# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-06-24 07:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablechangelogger', '0004_auto_20190529_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablechangeslog',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='tablechangeslog',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablechangeslog',
            name='property_unique_ids',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='tablechangeslog',
            name='unique_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
