# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-10-08 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablechangelogger', '0005_auto_20190624_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablechangeslog',
            name='unique_id',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
